apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-manager
  namespace: class
spec:
  replicas: 2
  selector:
    matchLabels:
      app: class-manager
  template:
    metadata:
      labels:
        app: class-manager
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: class-container
          image: didin8080/class-manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: regcred

