apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-ingress
  namespace: class
spec:
  ingressClassName: traefik
  rules:
    - host: lapzone.didin.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: class-service
                port:
                  number: 80
